import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'
import { AppContextProvider } from '@/lib/contexts'
import Table from '@/components/Table'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div> <Navigation /> </div>
       
        <div className='flex w-full'>{children}</div>
       
      </body>
    </html>
  )
}
