// components/RootLayout.tsx
import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavigationHeader from '@/components/Navigationheader';
import NavigationTrending from '@/components/Navigation';
import { AppContextProvider } from '@/lib/contexts';
import SideBar from '@/components/SideBar2';
import Table from '@/components/Table2';
import TopBar from '@/components/TopBar';  // Import the TopBar component

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <NavigationHeader />
            <NavigationTrending />

            <div style={{ display: 'flex', flex: 1, flexDirection: 'row' }}>
              <SideBar style={{ flex: '0 0 auto', width: '200px', background: '#f0f0f0', padding: '20px' }} />
              <div style={{ flex: 1, padding: '20px', overflow: 'auto' }}>
                <TopBar /> {/* Place the TopBar component here, inside the div containing the table */}
                <Table style={{ width: '100%' }} />
              </div>
            </div>

            <div style={{ flex: '0 0 auto', width: '100%', borderTop: '1px solid #ddd', padding: '20px' }}>
              {children}
            </div>
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
